import { GeneralLedgerEntry } from "./general-ledger-entry";

const COMPANY_BASE = {
  tenantId: '00000000-0000-0000-0000-000000000001',
  companyId: 'comp-001',
  companyCode: 'CMP01',
  companyName: 'SofaCraft Furnishings Pvt Ltd',
  branchId: 'branch-001',
  branchCode: 'BR01',
  branchName: 'Coimbatore',
  fiscalYearId: 'fy-2026',
  fiscalYearCode: 'FY26',
  fiscalYearName: 'FY 2025-26',
  baseCurrencyId: 'cur-INR',
  baseCurrencyCode: 'INR',
  baseCurrencyName: 'Indian Rupee',
  branchCodeSnapshot: 'BR01',
  branchNameSnapshot: 'Coimbatore',
  isReversal: false,
  isDeleted: false,
  createdBy: 'admin',
};

export const GENERAL_LEDGER_ENTRIES_SEED: GeneralLedgerEntry[] = [

  // ────────────────────────────────────────────────────────────────────
  // PINV-2026-001 · Purchase Invoice from Krishna Timber & Plywood (Teak Wood + Plywood)
  // Purchases Dr ₹480,000 / AP Cr ₹480,000 + GST Input Dr ₹86,400 / AP Cr ₹86,400
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-001-001',
    ledgerId: 'ledger-009', ledgerCode: 'LED09', ledgerName: 'Purchase Ledger',
    accountId: 'acc-017', accountCode: 'PURCH', accountName: 'Purchases Account',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-10', postingDate: '2026-01-10', postingSequenceNumber: 1,
    debitAmount: 480000, creditAmount: 0,
    sourceType: 'PurchaseInvoice', sourceDocumentId: 'PINV-2026-001', sourceDocumentNumber: 'PINV-2026-001',
    journalEntryId: 'je-pi-001', journalEntryNumber: 'JE-PI-001',
    journalLineId: 'jl-pi-001', journalLineNumber: 1,
    narration: 'Purchase of Teak Wood & Plywood from Krishna Timber & Plywood',
    lineNarration: 'Purchases account debited',
    accountCodeSnapshot: 'PURCH', accountNameSnapshot: 'Purchases Account',
    createdAt: '2026-01-10T10:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-001-002',
    ledgerId: 'ledger-010', ledgerCode: 'LED10', ledgerName: 'Tax Ledger',
    accountId: 'acc-018', accountCode: 'GSTIN', accountName: 'GST Input Credit',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-10', postingDate: '2026-01-10', postingSequenceNumber: 2,
    debitAmount: 86400, creditAmount: 0,
    sourceType: 'PurchaseInvoice', sourceDocumentId: 'PINV-2026-001', sourceDocumentNumber: 'PINV-2026-001',
    journalEntryId: 'je-pi-001', journalEntryNumber: 'JE-PI-001',
    journalLineId: 'jl-pi-002', journalLineNumber: 2,
    narration: 'Purchase of Teak Wood & Plywood from Krishna Timber & Plywood',
    lineNarration: 'GST input credit on purchase',
    accountCodeSnapshot: 'GSTIN', accountNameSnapshot: 'GST Input Credit',
    createdAt: '2026-01-10T10:01:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-001-003',
    ledgerId: 'ledger-008', ledgerCode: 'LED08', ledgerName: 'Payables Ledger',
    accountId: 'acc-013', accountCode: 'AP', accountName: 'Accounts Payable',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-10', postingDate: '2026-01-10', postingSequenceNumber: 3,
    debitAmount: 0, creditAmount: 566400,
    sourceType: 'PurchaseInvoice', sourceDocumentId: 'PINV-2026-001', sourceDocumentNumber: 'PINV-2026-001',
    journalEntryId: 'je-pi-001', journalEntryNumber: 'JE-PI-001',
    journalLineId: 'jl-pi-003', journalLineNumber: 3,
    narration: 'Purchase of Teak Wood & Plywood from Krishna Timber & Plywood',
    lineNarration: 'Accounts payable credited - Krishna Timber & Plywood',
    accountCodeSnapshot: 'AP', accountNameSnapshot: 'Accounts Payable',
    createdAt: '2026-01-10T10:02:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // INV-2026-001 · Sales Invoice to Sundaram Furnishings (3 Yashika 3+1+1 Sofa Set)
  // AR Dr ₹318,597 / Sales Cr ₹269,997 + GST Output Cr ₹48,600
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-002-001',
    ledgerId: 'ledger-004', ledgerCode: 'LED04', ledgerName: 'Receivables Ledger',
    accountId: 'acc-007', accountCode: 'AR', accountName: 'Accounts Receivable',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-10', postingDate: '2026-01-10', postingSequenceNumber: 4,
    debitAmount: 318597, creditAmount: 0,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-001', sourceDocumentNumber: 'INV-2026-001',
    journalEntryId: 'je-si-001', journalEntryNumber: 'JE-SI-001',
    journalLineId: 'jl-si-001', journalLineNumber: 1,
    narration: 'Sale of 3 Yashika 3+1+1 Sofa Set to Sundaram Furnishings',
    lineNarration: 'Accounts receivable debited',
    accountCodeSnapshot: 'AR', accountNameSnapshot: 'Accounts Receivable',
    createdAt: '2026-01-10T11:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-002-002',
    ledgerId: 'ledger-006', ledgerCode: 'LED06', ledgerName: 'Revenue Ledger',
    accountId: 'acc-009', accountCode: 'SALES', accountName: 'Sales Revenue Account',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-10', postingDate: '2026-01-10', postingSequenceNumber: 5,
    debitAmount: 0, creditAmount: 269997,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-001', sourceDocumentNumber: 'INV-2026-001',
    journalEntryId: 'je-si-001', journalEntryNumber: 'JE-SI-001',
    journalLineId: 'jl-si-002', journalLineNumber: 2,
    narration: 'Sale of 3 Yashika 3+1+1 Sofa Set to Sundaram Furnishings',
    lineNarration: 'Sales revenue credited',
    accountCodeSnapshot: 'SALES', accountNameSnapshot: 'Sales Revenue Account',
    createdAt: '2026-01-10T11:01:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-002-003',
    ledgerId: 'ledger-010', ledgerCode: 'LED10', ledgerName: 'Tax Ledger',
    accountId: 'acc-019', accountCode: 'GSTOUT', accountName: 'GST Output Liability',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-10', postingDate: '2026-01-10', postingSequenceNumber: 6,
    debitAmount: 0, creditAmount: 48600,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-001', sourceDocumentNumber: 'INV-2026-001',
    journalEntryId: 'je-si-001', journalEntryNumber: 'JE-SI-001',
    journalLineId: 'jl-si-003', journalLineNumber: 3,
    narration: 'Sale of 3 Yashika 3+1+1 Sofa Set to Sundaram Furnishings',
    lineNarration: 'GST output liability credited',
    accountCodeSnapshot: 'GSTOUT', accountNameSnapshot: 'GST Output Liability',
    createdAt: '2026-01-10T11:02:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // Payment received from Sundaram Furnishings for INV-2026-001
  // Bank Dr ₹318,597 / AR Cr ₹318,597
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-003-001',
    ledgerId: 'ledger-003', ledgerCode: 'LED03', ledgerName: 'Bank Ledger',
    accountId: 'acc-005', accountCode: 'BANK', accountName: 'Bank Account',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-15', postingDate: '2026-01-15', postingSequenceNumber: 7,
    debitAmount: 318597, creditAmount: 0,
    sourceType: 'CustomerPayment', sourceDocumentId: 'CP-001', sourceDocumentNumber: 'CP-001',
    journalEntryId: 'je-cp-001', journalEntryNumber: 'JE-CP-001',
    journalLineId: 'jl-cp-001', journalLineNumber: 1,
    narration: 'Payment received from Sundaram Furnishings for INV-2026-001',
    lineNarration: 'Bank debited on customer receipt',
    accountCodeSnapshot: 'BANK', accountNameSnapshot: 'Bank Account',
    createdAt: '2026-01-15T10:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-003-002',
    ledgerId: 'ledger-004', ledgerCode: 'LED04', ledgerName: 'Receivables Ledger',
    accountId: 'acc-007', accountCode: 'AR', accountName: 'Accounts Receivable',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-15', postingDate: '2026-01-15', postingSequenceNumber: 8,
    debitAmount: 0, creditAmount: 318597,
    sourceType: 'CustomerPayment', sourceDocumentId: 'CP-001', sourceDocumentNumber: 'CP-001',
    journalEntryId: 'je-cp-001', journalEntryNumber: 'JE-CP-001',
    journalLineId: 'jl-cp-002', journalLineNumber: 2,
    narration: 'Payment received from Sundaram Furnishings for INV-2026-001',
    lineNarration: 'AR cleared on receipt',
    accountCodeSnapshot: 'AR', accountNameSnapshot: 'Accounts Receivable',
    createdAt: '2026-01-15T10:01:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // Payment to Krishna Timber & Plywood for PINV-2026-001
  // AP Dr ₹566,400 / Bank Cr ₹566,400
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-004-001',
    ledgerId: 'ledger-008', ledgerCode: 'LED08', ledgerName: 'Payables Ledger',
    accountId: 'acc-013', accountCode: 'AP', accountName: 'Accounts Payable',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-18', postingDate: '2026-01-18', postingSequenceNumber: 9,
    debitAmount: 566400, creditAmount: 0,
    sourceType: 'VendorPayment', sourceDocumentId: 'VP-001', sourceDocumentNumber: 'VP-001',
    journalEntryId: 'je-vp-001', journalEntryNumber: 'JE-VP-001',
    journalLineId: 'jl-vp-001', journalLineNumber: 1,
    narration: 'Payment to Krishna Timber & Plywood for PINV-2026-001',
    lineNarration: 'AP cleared on vendor payment',
    accountCodeSnapshot: 'AP', accountNameSnapshot: 'Accounts Payable',
    createdAt: '2026-01-18T14:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-004-002',
    ledgerId: 'ledger-003', ledgerCode: 'LED03', ledgerName: 'Bank Ledger',
    accountId: 'acc-005', accountCode: 'BANK', accountName: 'Bank Account',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-18', postingDate: '2026-01-18', postingSequenceNumber: 10,
    debitAmount: 0, creditAmount: 566400,
    sourceType: 'VendorPayment', sourceDocumentId: 'VP-001', sourceDocumentNumber: 'VP-001',
    journalEntryId: 'je-vp-001', journalEntryNumber: 'JE-VP-001',
    journalLineId: 'jl-vp-002', journalLineNumber: 2,
    narration: 'Payment to Krishna Timber & Plywood for PINV-2026-001',
    lineNarration: 'Bank credited for vendor payment',
    accountCodeSnapshot: 'BANK', accountNameSnapshot: 'Bank Account',
    createdAt: '2026-01-18T14:01:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // INV-2026-002 · Sales to Deepa Interiors & Decor (5 Royal Single Recliner)
  // AR Dr ₹196,170 / Sales Cr ₹166,245 + GST Output Cr ₹29,924
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-005-001',
    ledgerId: 'ledger-004', ledgerCode: 'LED04', ledgerName: 'Receivables Ledger',
    accountId: 'acc-007', accountCode: 'AR', accountName: 'Accounts Receivable',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-15', postingDate: '2026-01-15', postingSequenceNumber: 11,
    debitAmount: 196170, creditAmount: 0,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-002', sourceDocumentNumber: 'INV-2026-002',
    journalEntryId: 'je-si-002', journalEntryNumber: 'JE-SI-002',
    journalLineId: 'jl-si-004', journalLineNumber: 1,
    narration: 'Sale of 5 Royal Single Recliner to Deepa Interiors & Decor',
    lineNarration: 'AR debited',
    accountCodeSnapshot: 'AR', accountNameSnapshot: 'Accounts Receivable',
    createdAt: '2026-01-15T14:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-005-002',
    ledgerId: 'ledger-006', ledgerCode: 'LED06', ledgerName: 'Revenue Ledger',
    accountId: 'acc-009', accountCode: 'SALES', accountName: 'Sales Revenue Account',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-15', postingDate: '2026-01-15', postingSequenceNumber: 12,
    debitAmount: 0, creditAmount: 166245,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-002', sourceDocumentNumber: 'INV-2026-002',
    journalEntryId: 'je-si-002', journalEntryNumber: 'JE-SI-002',
    journalLineId: 'jl-si-005', journalLineNumber: 2,
    narration: 'Sale of 5 Royal Single Recliner to Deepa Interiors & Decor',
    lineNarration: 'Sales revenue credited',
    accountCodeSnapshot: 'SALES', accountNameSnapshot: 'Sales Revenue Account',
    createdAt: '2026-01-15T14:01:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-005-003',
    ledgerId: 'ledger-010', ledgerCode: 'LED10', ledgerName: 'Tax Ledger',
    accountId: 'acc-019', accountCode: 'GSTOUT', accountName: 'GST Output Liability',
    accountingPeriodId: 'jan-2026', accountingPeriodCode: 'JAN', accountingPeriodName: 'January 2026',
    entryDate: '2026-01-15', postingDate: '2026-01-15', postingSequenceNumber: 13,
    debitAmount: 0, creditAmount: 29924,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-002', sourceDocumentNumber: 'INV-2026-002',
    journalEntryId: 'je-si-002', journalEntryNumber: 'JE-SI-002',
    journalLineId: 'jl-si-006', journalLineNumber: 3,
    narration: 'Sale of 5 Royal Single Recliner to Deepa Interiors & Decor',
    lineNarration: 'GST output liability credited',
    accountCodeSnapshot: 'GSTOUT', accountNameSnapshot: 'GST Output Liability',
    createdAt: '2026-01-15T14:02:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // JE-003 · Factory Rent Expense Paid (Feb 2026)
  // Rent Dr ₹25,000 / Bank Cr ₹25,000
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-006-001',
    ledgerId: 'ledger-002', ledgerCode: 'LED02', ledgerName: 'Expense Ledger',
    accountId: 'acc-003', accountCode: 'RENT', accountName: 'Rent Expense Account',
    accountingPeriodId: 'feb-2026', accountingPeriodCode: 'FEB', accountingPeriodName: 'February 2026',
    entryDate: '2026-02-05', postingDate: '2026-02-05', postingSequenceNumber: 14,
    debitAmount: 25000, creditAmount: 0,
    sourceType: 'JournalEntry', sourceDocumentId: 'doc-003', sourceDocumentNumber: 'JV-003',
    journalEntryId: 'je-003', journalEntryNumber: 'JE-003',
    journalLineId: 'jl-003', journalLineNumber: 1,
    narration: 'Factory rent paid for February 2026',
    lineNarration: 'Rent expense debited',
    accountCodeSnapshot: 'RENT', accountNameSnapshot: 'Rent Expense Account',
    createdAt: '2026-02-05T09:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-006-002',
    ledgerId: 'ledger-003', ledgerCode: 'LED03', ledgerName: 'Bank Ledger',
    accountId: 'acc-005', accountCode: 'BANK', accountName: 'Bank Account',
    accountingPeriodId: 'feb-2026', accountingPeriodCode: 'FEB', accountingPeriodName: 'February 2026',
    entryDate: '2026-02-05', postingDate: '2026-02-05', postingSequenceNumber: 15,
    debitAmount: 0, creditAmount: 25000,
    sourceType: 'JournalEntry', sourceDocumentId: 'doc-003', sourceDocumentNumber: 'JV-003',
    journalEntryId: 'je-003', journalEntryNumber: 'JE-003',
    journalLineId: 'jl-004', journalLineNumber: 2,
    narration: 'Factory rent paid for February 2026',
    lineNarration: 'Bank credited for rent payment',
    accountCodeSnapshot: 'BANK', accountNameSnapshot: 'Bank Account',
    createdAt: '2026-02-05T09:01:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // INV-2026-004 · Sales to Sundaram Furnishings (4 Executive High-Back Chair)
  // AR Dr ₹89,675 / Sales Cr ₹75,996 + GST Output Cr ₹13,679
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-007-001',
    ledgerId: 'ledger-004', ledgerCode: 'LED04', ledgerName: 'Receivables Ledger',
    accountId: 'acc-007', accountCode: 'AR', accountName: 'Accounts Receivable',
    accountingPeriodId: 'feb-2026', accountingPeriodCode: 'FEB', accountingPeriodName: 'February 2026',
    entryDate: '2026-02-15', postingDate: '2026-02-15', postingSequenceNumber: 16,
    debitAmount: 89675, creditAmount: 0,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-004', sourceDocumentNumber: 'INV-2026-004',
    journalEntryId: 'je-si-004', journalEntryNumber: 'JE-SI-004',
    journalLineId: 'jl-si-010', journalLineNumber: 1,
    narration: 'Sale of 4 Executive High-Back Chair to Sundaram Furnishings',
    lineNarration: 'AR debited',
    accountCodeSnapshot: 'AR', accountNameSnapshot: 'Accounts Receivable',
    createdAt: '2026-02-15T15:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-007-002',
    ledgerId: 'ledger-006', ledgerCode: 'LED06', ledgerName: 'Revenue Ledger',
    accountId: 'acc-009', accountCode: 'SALES', accountName: 'Sales Revenue Account',
    accountingPeriodId: 'feb-2026', accountingPeriodCode: 'FEB', accountingPeriodName: 'February 2026',
    entryDate: '2026-02-15', postingDate: '2026-02-15', postingSequenceNumber: 17,
    debitAmount: 0, creditAmount: 75996,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-004', sourceDocumentNumber: 'INV-2026-004',
    journalEntryId: 'je-si-004', journalEntryNumber: 'JE-SI-004',
    journalLineId: 'jl-si-011', journalLineNumber: 2,
    narration: 'Sale of 4 Executive High-Back Chair to Sundaram Furnishings',
    lineNarration: 'Sales revenue credited',
    accountCodeSnapshot: 'SALES', accountNameSnapshot: 'Sales Revenue Account',
    createdAt: '2026-02-15T15:01:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-007-003',
    ledgerId: 'ledger-010', ledgerCode: 'LED10', ledgerName: 'Tax Ledger',
    accountId: 'acc-019', accountCode: 'GSTOUT', accountName: 'GST Output Liability',
    accountingPeriodId: 'feb-2026', accountingPeriodCode: 'FEB', accountingPeriodName: 'February 2026',
    entryDate: '2026-02-15', postingDate: '2026-02-15', postingSequenceNumber: 18,
    debitAmount: 0, creditAmount: 13679,
    sourceType: 'SalesInvoice', sourceDocumentId: 'INV-2026-004', sourceDocumentNumber: 'INV-2026-004',
    journalEntryId: 'je-si-004', journalEntryNumber: 'JE-SI-004',
    journalLineId: 'jl-si-012', journalLineNumber: 3,
    narration: 'Sale of 4 Executive High-Back Chair to Sundaram Furnishings',
    lineNarration: 'GST output liability credited',
    accountCodeSnapshot: 'GSTOUT', accountNameSnapshot: 'GST Output Liability',
    createdAt: '2026-02-15T15:02:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // JE-004 · Salary Expense (Feb 2026)
  // Salary Dr ₹150,000 / Bank Cr ₹150,000
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-008-001',
    ledgerId: 'ledger-002', ledgerCode: 'LED02', ledgerName: 'Expense Ledger',
    accountId: 'acc-006', accountCode: 'SAL', accountName: 'Salary Expense Account',
    accountingPeriodId: 'feb-2026', accountingPeriodCode: 'FEB', accountingPeriodName: 'February 2026',
    entryDate: '2026-02-28', postingDate: '2026-02-28', postingSequenceNumber: 19,
    debitAmount: 150000, creditAmount: 0,
    sourceType: 'JournalEntry', sourceDocumentId: 'doc-004', sourceDocumentNumber: 'JV-004',
    journalEntryId: 'je-004', journalEntryNumber: 'JE-004',
    journalLineId: 'jl-007', journalLineNumber: 1,
    narration: 'Salary paid for February 2026',
    lineNarration: 'Salary expense debited',
    accountCodeSnapshot: 'SAL', accountNameSnapshot: 'Salary Expense Account',
    createdAt: '2026-02-28T18:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-008-002',
    ledgerId: 'ledger-003', ledgerCode: 'LED03', ledgerName: 'Bank Ledger',
    accountId: 'acc-005', accountCode: 'BANK', accountName: 'Bank Account',
    accountingPeriodId: 'feb-2026', accountingPeriodCode: 'FEB', accountingPeriodName: 'February 2026',
    entryDate: '2026-02-28', postingDate: '2026-02-28', postingSequenceNumber: 20,
    debitAmount: 0, creditAmount: 150000,
    sourceType: 'JournalEntry', sourceDocumentId: 'doc-004', sourceDocumentNumber: 'JV-004',
    journalEntryId: 'je-004', journalEntryNumber: 'JE-004',
    journalLineId: 'jl-008', journalLineNumber: 2,
    narration: 'Salary paid for February 2026',
    lineNarration: 'Bank credited for salary disbursement',
    accountCodeSnapshot: 'BANK', accountNameSnapshot: 'Bank Account',
    createdAt: '2026-02-28T18:01:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // PC-007 · Petty Cash Expense - Factory Supplies (Posted)
  // Office Supplies Dr ₹1,200 / Petty Cash Cr ₹1,200
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-009-001',
    ledgerId: 'ledger-002', ledgerCode: 'LED02', ledgerName: 'Expense Ledger',
    accountId: 'acc-004', accountCode: 'OFFSUP', accountName: 'Office Supplies Expense',
    accountingPeriodId: 'apr-2026', accountingPeriodCode: 'APR', accountingPeriodName: 'April 2026',
    entryDate: '2026-04-02', postingDate: '2026-04-03', postingSequenceNumber: 21,
    debitAmount: 1200, creditAmount: 0,
    sourceType: 'PettyCash', sourceDocumentId: 'PC007', sourceDocumentNumber: 'PC-007',
    journalEntryId: 'je-pc-001', journalEntryNumber: 'JE-PC-001',
    journalLineId: 'jl-pc-001', journalLineNumber: 1,
    narration: 'Petty cash factory supplies expense – Priya Sharma (EMP002)',
    lineNarration: 'Factory supplies expense debited',
    accountCodeSnapshot: 'OFFSUP', accountNameSnapshot: 'Office Supplies Expense',
    createdAt: '2026-04-03T09:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-009-002',
    ledgerId: 'ledger-005', ledgerCode: 'LED05', ledgerName: 'Petty Cash Ledger',
    accountId: 'acc-008', accountCode: 'PC', accountName: 'Petty Cash Account',
    accountingPeriodId: 'apr-2026', accountingPeriodCode: 'APR', accountingPeriodName: 'April 2026',
    entryDate: '2026-04-02', postingDate: '2026-04-03', postingSequenceNumber: 22,
    debitAmount: 0, creditAmount: 1200,
    sourceType: 'PettyCash', sourceDocumentId: 'PC007', sourceDocumentNumber: 'PC-007',
    journalEntryId: 'je-pc-001', journalEntryNumber: 'JE-PC-001',
    journalLineId: 'jl-pc-002', journalLineNumber: 2,
    narration: 'Petty cash factory supplies expense – Priya Sharma (EMP002)',
    lineNarration: 'Petty cash account credited',
    accountCodeSnapshot: 'PC', accountNameSnapshot: 'Petty Cash Account',
    createdAt: '2026-04-03T09:01:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // PC-008 · Petty Cash Expense - Parking (Posted)
  // Office Supplies Dr ₹300 / Petty Cash Cr ₹300
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-010-001',
    ledgerId: 'ledger-002', ledgerCode: 'LED02', ledgerName: 'Expense Ledger',
    accountId: 'acc-004', accountCode: 'OFFSUP', accountName: 'Office Supplies Expense',
    accountingPeriodId: 'apr-2026', accountingPeriodCode: 'APR', accountingPeriodName: 'April 2026',
    entryDate: '2026-04-04', postingDate: '2026-04-05', postingSequenceNumber: 23,
    debitAmount: 300, creditAmount: 0,
    sourceType: 'PettyCash', sourceDocumentId: 'PC008', sourceDocumentNumber: 'PC-008',
    journalEntryId: 'je-pc-002', journalEntryNumber: 'JE-PC-002',
    journalLineId: 'jl-pc-003', journalLineNumber: 1,
    narration: 'Petty cash parking charges – Sneha Reddy (EMP004)',
    lineNarration: 'Parking expense debited',
    accountCodeSnapshot: 'OFFSUP', accountNameSnapshot: 'Office Supplies Expense',
    createdAt: '2026-04-05T10:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-010-002',
    ledgerId: 'ledger-005', ledgerCode: 'LED05', ledgerName: 'Petty Cash Ledger',
    accountId: 'acc-008', accountCode: 'PC', accountName: 'Petty Cash Account',
    accountingPeriodId: 'apr-2026', accountingPeriodCode: 'APR', accountingPeriodName: 'April 2026',
    entryDate: '2026-04-04', postingDate: '2026-04-05', postingSequenceNumber: 24,
    debitAmount: 0, creditAmount: 300,
    sourceType: 'PettyCash', sourceDocumentId: 'PC008', sourceDocumentNumber: 'PC-008',
    journalEntryId: 'je-pc-002', journalEntryNumber: 'JE-PC-002',
    journalLineId: 'jl-pc-004', journalLineNumber: 2,
    narration: 'Petty cash parking charges – Sneha Reddy (EMP004)',
    lineNarration: 'Petty cash account credited',
    accountCodeSnapshot: 'PC', accountNameSnapshot: 'Petty Cash Account',
    createdAt: '2026-04-05T10:01:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // SAL-2026-APR-001 · Salary Expense (April 2026)
  // Salary Dr ₹87,000 / Bank Cr ₹87,000
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-011-001',
    ledgerId: 'ledger-002', ledgerCode: 'LED02', ledgerName: 'Expense Ledger',
    accountId: 'acc-006', accountCode: 'SAL', accountName: 'Salary Expense Account',
    accountingPeriodId: 'apr-2026', accountingPeriodCode: 'APR', accountingPeriodName: 'April 2026',
    entryDate: '2026-05-05', postingDate: '2026-05-05', postingSequenceNumber: 25,
    debitAmount: 87000, creditAmount: 0,
    sourceType: 'SalaryPayment', sourceDocumentId: 'SAL001', sourceDocumentNumber: 'SAL-2026-APR-001',
    journalEntryId: 'je-sal-001', journalEntryNumber: 'JE-SAL-001',
    journalLineId: 'jl-sal-001', journalLineNumber: 1,
    narration: 'Salary paid for April 2026 – 3 employees',
    lineNarration: 'Salary expense debited',
    accountCodeSnapshot: 'SAL', accountNameSnapshot: 'Salary Expense Account',
    createdAt: '2026-05-05T10:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-011-002',
    ledgerId: 'ledger-003', ledgerCode: 'LED03', ledgerName: 'Bank Ledger',
    accountId: 'acc-005', accountCode: 'BANK', accountName: 'Bank Account',
    accountingPeriodId: 'apr-2026', accountingPeriodCode: 'APR', accountingPeriodName: 'April 2026',
    entryDate: '2026-05-05', postingDate: '2026-05-05', postingSequenceNumber: 26,
    debitAmount: 0, creditAmount: 87000,
    sourceType: 'SalaryPayment', sourceDocumentId: 'SAL001', sourceDocumentNumber: 'SAL-2026-APR-001',
    journalEntryId: 'je-sal-001', journalEntryNumber: 'JE-SAL-001',
    journalLineId: 'jl-sal-002', journalLineNumber: 2,
    narration: 'Salary paid for April 2026 – 3 employees',
    lineNarration: 'Bank credited for salary disbursement',
    accountCodeSnapshot: 'BANK', accountNameSnapshot: 'Bank Account',
    createdAt: '2026-05-05T10:01:00',
  },

  // ────────────────────────────────────────────────────────────────────
  // PC-011 · Petty Cash Replenishment
  // Petty Cash Dr ₹27,500 / Bank Cr ₹27,500
  // ────────────────────────────────────────────────────────────────────
  {
    ...COMPANY_BASE,
    id: 'gl-012-001',
    ledgerId: 'ledger-005', ledgerCode: 'LED05', ledgerName: 'Petty Cash Ledger',
    accountId: 'acc-008', accountCode: 'PC', accountName: 'Petty Cash Account',
    accountingPeriodId: 'jun-2026', accountingPeriodCode: 'JUN', accountingPeriodName: 'June 2026',
    entryDate: '2026-06-01', postingDate: '2026-06-01', postingSequenceNumber: 27,
    debitAmount: 27500, creditAmount: 0,
    sourceType: 'PettyCash', sourceDocumentId: 'PC011', sourceDocumentNumber: 'PC-011',
    journalEntryId: 'je-pc-003', journalEntryNumber: 'JE-PC-003',
    journalLineId: 'jl-pc-005', journalLineNumber: 1,
    narration: 'Petty cash replenishment – Arun Kumar (EMP001)',
    lineNarration: 'Petty cash account debited for replenishment',
    accountCodeSnapshot: 'PC', accountNameSnapshot: 'Petty Cash Account',
    createdAt: '2026-06-01T09:00:00',
  },
  {
    ...COMPANY_BASE,
    id: 'gl-012-002',
    ledgerId: 'ledger-003', ledgerCode: 'LED03', ledgerName: 'Bank Ledger',
    accountId: 'acc-005', accountCode: 'BANK', accountName: 'Bank Account',
    accountingPeriodId: 'jun-2026', accountingPeriodCode: 'JUN', accountingPeriodName: 'June 2026',
    entryDate: '2026-06-01', postingDate: '2026-06-01', postingSequenceNumber: 28,
    debitAmount: 0, creditAmount: 27500,
    sourceType: 'PettyCash', sourceDocumentId: 'PC011', sourceDocumentNumber: 'PC-011',
    journalEntryId: 'je-pc-003', journalEntryNumber: 'JE-PC-003',
    journalLineId: 'jl-pc-006', journalLineNumber: 2,
    narration: 'Petty cash replenishment – Arun Kumar (EMP001)',
    lineNarration: 'Bank credited for petty cash replenishment',
    accountCodeSnapshot: 'PC', accountNameSnapshot: 'Petty Cash Account',
    createdAt: '2026-06-01T09:01:00',
  },
];
