import { SalesInvoice } from "./sales-invoice";

const COMPANY = {
    companyName: 'SofaCraft Furnishings Pvt Ltd',
    companyGSTIN: '33AABCS1234L1Z5',
    companyPAN: 'AABCS1234L',
    companyAddress: '42, Industrial Estate, Ambattur, Chennai - 600058',
    companyState: 'Tamil Nadu',
    companyPhone: '+91 44 2345 6789',
    companyEmail: 'billing@sofacraft.in',
};

export const SAMPLE_INVOICES: SalesInvoice[] = [
  {
    id: 1,
    invoiceNumber: 'INV-2026-001',
    invoiceDate: '2026-01-05',
    dueDate: '2026-02-04',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: {
      bankName: 'Indian Bank',
      accountNumber: '1234567890',
      ifscCode: 'IDIB000A001',
      branch: 'Ambattur',
      upiId: 'sofacraft@upi',
    },
    financialYear: 'FY 2025-26',
    referencePONo: 'PO-001',
    currency: 'INR',
    exchangeRate: 1,
    status: 'paid',
    eWayBillNo: 'EWB1001',
    deliveryNote: 'Delivered',
    modeTermsOfPayment: 'NEFT',
    buyerOrderNo: 'BO-001',
    buyerOrderDate: '2026-01-03',
    otherReferences: 'REF-001',
    dispatchDocNo: 'DOC-001',
    deliveryNoteDate: '2026-01-05',
    dispatchedThrough: 'Road',
    destination: 'Madurai',
    billOfLadingNo: 'BL-001',
    motorVehicleNo: 'TN01AB1234',
    termsOfDelivery: 'Immediate',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C001',
    customerName: 'Arjun Traders',
    billingAddress: 'Anna Nagar, Chennai',
    shippingAddress: 'Anna Nagar, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600040',
    customerGSTIN: '33ABCDE1234F1Z5',
    customerPAN: 'ABCDE1234F',
    phoneEmail: '+91 9876543210 | arjun@gmail.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1,
        productId: 'P001',
        productCode: 'PRD001',
        itemName: 'Plywood Sheet',
        hsnSacCode: '4412',
        quantity: 10,
        unitOfMeasure: 'Nos',
        unitPrice: 1000,
        unitId: 1,
        taxPercent: 18,
        discountPercent: 0,
        taxableAmount: 10000,
        gstRate: 18,
        cgstAmount: 900,
        sgstAmount: 900,
        igstAmount: 0,
        lineTotal: 11800,
        batchSerialNo: 'B001',
        taxId: 'T18',
        errProduct: false,
        errQty: false,
        errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      {
        hsnSacCode: '4412',
        taxableValue: 10000,
        cgstRate: 9,
        cgstAmount: 900,
        sgstRate: 9,
        sgstAmount: 900,
        igstRate: 0,
        igstAmount: 0,
        totalTaxAmount: 1800,
      },
    ],
    taxSummary: {
      subTotal: 10000,
      totalTaxableValue: 10000,
      totalCGST: 900,
      totalSGST: 900,
      totalIGST: 0,
      totalTaxAmount: 1800,
      grandTotal: 11800,
      roundOff: 0,
      invoiceTotal: 11800,
      amountInWords: 'Rupees Eleven Thousand Eight Hundred Only',
    },
    payment: {
      paymentTerms: 'net30',
      paymentMode: 'neft',
      amountPaid: 11800,
      paymentDate: '2026-01-10',
      transactionRefNo: 'TXN001',
      balanceDue: 0,
      overdueDays: 0,
      lateFeeInterest: 0,
      paymentStatus: 'paid',
    },
    declaration: 'All details are true and correct.',
    notes: 'Payment received.',
    createdAt: '2026-01-05',
    updatedAt: '2026-01-10',
  },

  {
    id: 2,
    invoiceNumber: 'INV-2026-002',
    invoiceDate: '2026-01-06',
    dueDate: '2026-02-05',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'duplicate',
    companyBankDetails: {
      bankName: 'HDFC Bank',
      accountNumber: '2233445566',
      ifscCode: 'HDFC0000123',
      branch: 'Anna Nagar',
      upiId: 'sofa@upi',
    },
    financialYear: 'FY 2025-26',
    referencePONo: 'PO-002',
    currency: 'INR',
    exchangeRate: 1,
    status: 'partially_paid',
    eWayBillNo: 'EWB1002',
    deliveryNote: 'Partially Delivered',
    modeTermsOfPayment: 'Cash',
    buyerOrderNo: 'BO-002',
    buyerOrderDate: '2026-01-04',
    otherReferences: 'REF-002',
    dispatchDocNo: 'DOC-002',
    deliveryNoteDate: '2026-01-06',
    dispatchedThrough: 'Courier',
    destination: 'Salem',
    billOfLadingNo: 'BL-002',
    motorVehicleNo: 'TN02CD5678',
    termsOfDelivery: 'Within 7 Days',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C002',
    customerName: 'Lakshmi Builders',
    billingAddress: 'Tambaram, Chennai',
    shippingAddress: 'Tambaram, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600045',
    customerGSTIN: '33AAAAA2222A1Z5',
    customerPAN: 'AAAAA2222A',
    phoneEmail: '+91 9999999999 | lakshmi@gmail.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1,
        productId: 'P002',
        productCode: 'PRD002',
        itemName: 'Steel Rod',
        hsnSacCode: '7213',
        quantity: 20,
        unitOfMeasure: 'Kg',
        unitPrice: 500,
        unitId: 1,
        taxPercent: 18,
        discountPercent: 5,
        taxableAmount: 9500,
        gstRate: 18,
        cgstAmount: 855,
        sgstAmount: 855,
        igstAmount: 0,
        lineTotal: 11210,
        batchSerialNo: 'B002',
        taxId: 'T18',
        errProduct: false,
        errQty: false,
        errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      {
        hsnSacCode: '7213',
        taxableValue: 9500,
        cgstRate: 9,
        cgstAmount: 855,
        sgstRate: 9,
        sgstAmount: 855,
        igstRate: 0,
        igstAmount: 0,
        totalTaxAmount: 1710,
      },
    ],
    taxSummary: {
      subTotal: 10000,
      totalTaxableValue: 9500,
      totalCGST: 855,
      totalSGST: 855,
      totalIGST: 0,
      totalTaxAmount: 1710,
      grandTotal: 11210,
      roundOff: 0,
      invoiceTotal: 11210,
      amountInWords: 'Rupees Eleven Thousand Two Hundred Ten Only',
    },
    payment: {
      paymentTerms: 'net30',
      paymentMode: 'cash',
      amountPaid: 5000,
      paymentDate: '2026-01-12',
      transactionRefNo: 'TXN002',
      balanceDue: 6210,
      overdueDays: 0,
      lateFeeInterest: 0,
      paymentStatus: 'partial',
    },
    declaration: 'Certified true copy.',
    notes: 'Partial payment received.',
    createdAt: '2026-01-06',
    updatedAt: '2026-01-12',
  },

  {
    id: 3,
    invoiceNumber: 'INV-2026-003',
    invoiceDate: '2026-01-07',
    dueDate: '2026-02-06',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'triplicate',
    companyBankDetails: {
      bankName: 'Axis Bank',
      accountNumber: '3344556677',
      ifscCode: 'UTIB0000123',
      branch: 'Velachery',
      upiId: 'axis@upi',
    },
    financialYear: 'FY 2025-26',
    referencePONo: 'PO-003',
    currency: 'INR',
    exchangeRate: 1,
    status: 'draft',
    eWayBillNo: 'EWB1003',
    deliveryNote: 'Pending',
    modeTermsOfPayment: 'UPI',
    buyerOrderNo: 'BO-003',
    buyerOrderDate: '2026-01-05',
    otherReferences: 'REF-003',
    dispatchDocNo: 'DOC-003',
    deliveryNoteDate: '2026-01-07',
    dispatchedThrough: 'Road',
    destination: 'Trichy',
    billOfLadingNo: 'BL-003',
    motorVehicleNo: 'TN03EF9999',
    termsOfDelivery: 'Advance',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C003',
    customerName: 'Modern Interiors',
    billingAddress: 'Velachery, Chennai',
    shippingAddress: 'Velachery, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600042',
    customerGSTIN: '33BBBBB3333B1Z5',
    customerPAN: 'BBBBB3333B',
    phoneEmail: '+91 8888888888 | modern@gmail.com',
    placeOfSupply: 'TN',
    lineItems: [],
    hsnWiseTaxSummary: [],
    taxSummary: {
      subTotal: 0,
      totalTaxableValue: 0,
      totalCGST: 0,
      totalSGST: 0,
      totalIGST: 0,
      totalTaxAmount: 0,
      grandTotal: 0,
      roundOff: 0,
      invoiceTotal: 0,
      amountInWords: 'Zero Only',
    },
    payment: {
      paymentTerms: 'net15',
      paymentMode: '',
      amountPaid: 0,
      paymentDate: '',
      transactionRefNo: '',
      balanceDue: 0,
      overdueDays: 0,
      lateFeeInterest: 0,
      paymentStatus: 'unpaid',
    },
    declaration: 'Subject to Chennai jurisdiction.',
    notes: 'Draft invoice.',
    createdAt: '2026-01-07',
    updatedAt: '2026-01-07',
  },

  // copy same structure and change values

  {
    id: 4,
    invoiceNumber: 'INV-2026-004',
    invoiceDate: '2026-01-08',
    dueDate: '2026-02-07',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: {
      bankName: 'SBI',
      accountNumber: '4455667788',
      ifscCode: 'SBIN0000456',
      branch: 'Porur',
      upiId: 'sbi@upi',
    },
    financialYear: 'FY 2025-26',
    referencePONo: 'PO-004',
    currency: 'INR',
    exchangeRate: 1,
    status: 'sent',
    eWayBillNo: 'EWB1004',
    deliveryNote: 'Dispatched',
    modeTermsOfPayment: 'Cheque',
    buyerOrderNo: 'BO-004',
    buyerOrderDate: '2026-01-06',
    otherReferences: 'REF-004',
    dispatchDocNo: 'DOC-004',
    deliveryNoteDate: '2026-01-08',
    dispatchedThrough: 'Courier',
    destination: 'Coimbatore',
    billOfLadingNo: 'BL-004',
    motorVehicleNo: 'TN04GH1234',
    termsOfDelivery: '7 Days',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C004',
    customerName: 'Raja Steels',
    billingAddress: 'Porur, Chennai',
    shippingAddress: 'Porur, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600116',
    customerGSTIN: '33CCCCC4444C1Z5',
    customerPAN: 'CCCCC4444C',
    phoneEmail: '+91 7777777777 | raja@gmail.com',
    placeOfSupply: 'TN',
    lineItems: [],
    hsnWiseTaxSummary: [],
    taxSummary: {
      subTotal: 5000,
      totalTaxableValue: 5000,
      totalCGST: 450,
      totalSGST: 450,
      totalIGST: 0,
      totalTaxAmount: 900,
      grandTotal: 5900,
      roundOff: 0,
      invoiceTotal: 5900,
      amountInWords: 'Rupees Five Thousand Nine Hundred Only',
    },
    payment: {
      paymentTerms: 'net15',
      paymentMode: 'cheque',
      amountPaid: 0,
      paymentDate: '',
      transactionRefNo: '',
      balanceDue: 5900,
      overdueDays: 0,
      lateFeeInterest: 0,
      paymentStatus: 'unpaid',
    },
    declaration: 'Goods once sold will not be taken back.',
    notes: 'Awaiting payment.',
    createdAt: '2026-01-08',
    updatedAt: '2026-01-08',
  }
];