import { SalesInvoice } from "./sales-invoice";

const COMPANY = {
    companyName: 'SofaCraft Furnishings Pvt Ltd',
    companyGSTIN: '33AABCS1234L1Z5',
    companyPAN: 'AABCS1234L',
    companyAddress: '42, Industrial Estate, Ambattur, Chennai - 600058',
    companyState: 'Tamil Nadu',
    companyPhone: '+91 44 2345 6789',
    companyEmail: 'billing@sofacraft.in',
};

const BANK_INDIAN = {
    bankName: 'Indian Bank', accountNumber: '1234567890',
    ifscCode: 'IDIB000A001', branch: 'Ambattur', upiId: 'sofacraft@upi',
};

const BANK_HDFC = {
    bankName: 'HDFC Bank', accountNumber: '2233445566',
    ifscCode: 'HDFC0000123', branch: 'Anna Nagar', upiId: 'sofa@upi',
};

const BANK_AXIS = {
    bankName: 'Axis Bank', accountNumber: '3344556677',
    ifscCode: 'UTIB0000123', branch: 'Velachery', upiId: 'axis@upi',
};

const BANK_SBI = {
    bankName: 'SBI', accountNumber: '4455667788',
    ifscCode: 'SBIN0000456', branch: 'Porur', upiId: 'sbi@upi',
};

export const SAMPLE_INVOICES: SalesInvoice[] = [

  // ════════════════════════════════════════════════════════════════════
  //  1 ─ PAID  ──  Arjun Traders  ──  5 × Laptop Pro 15
  // ════════════════════════════════════════════════════════════════════
  {
    id: 1,
    invoiceNumber: 'INV-2026-001',
    invoiceDate: '2026-01-10',
    dueDate: '2026-02-09',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_INDIAN,
    financialYear: 'FY 2025-26',
    referencePONo: 'CPO-001',
    currency: 'INR',
    exchangeRate: 1,
    status: 'paid',
    eWayBillNo: 'EWB1001',
    deliveryNote: 'Delivered',
    modeTermsOfPayment: 'NEFT',
    buyerOrderNo: 'BO-001',
    buyerOrderDate: '2026-01-08',
    otherReferences: 'REF-001',
    dispatchDocNo: 'DOC-001',
    deliveryNoteDate: '2026-01-10',
    dispatchedThrough: 'Road',
    destination: 'Chennai',
    billOfLadingNo: 'BL-001',
    motorVehicleNo: 'TN01AB1234',
    termsOfDelivery: 'Immediate',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C001',
    customerName: 'Arjun Traders Pvt Ltd',
    billingAddress: 'T Nagar, Chennai',
    shippingAddress: 'T Nagar, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600017',
    customerGSTIN: '33ABCDE1234F1Z5',
    customerPAN: 'ABCDE1234F',
    phoneEmail: '+91 9876543210 | arjun@traders.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-001', productCode: 'ELEC001',
        itemName: 'Laptop Pro 15', hsnSacCode: '8471',
        quantity: 5, unitOfMeasure: 'Pcs', unitPrice: 55000, unitId: 1,
        taxPercent: 18, discountPercent: 0, taxableAmount: 275000,
        gstRate: 18, cgstAmount: 24750, sgstAmount: 24750, igstAmount: 0,
        lineTotal: 324500, batchSerialNo: 'B001', taxId: 'T18',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '8471', taxableValue: 275000, cgstRate: 9, cgstAmount: 24750, sgstRate: 9, sgstAmount: 24750, igstRate: 0, igstAmount: 0, totalTaxAmount: 49500 },
    ],
    taxSummary: {
      subTotal: 275000, totalTaxableValue: 275000,
      totalCGST: 24750, totalSGST: 24750, totalIGST: 0,
      totalTaxAmount: 49500, grandTotal: 324500, roundOff: 0,
      invoiceTotal: 324500,
      amountInWords: 'Rupees Three Lakh Twenty Four Thousand Five Hundred Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: 'neft',
      amountPaid: 324500, paymentDate: '2026-01-15',
      transactionRefNo: 'TXN001', balanceDue: 0,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'paid',
    },
    declaration: 'All details are true and correct.',
    notes: 'Payment received via NEFT.',
    createdAt: '2026-01-10', updatedAt: '2026-01-15',
  },

  // ════════════════════════════════════════════════════════════════════
  //  2 ─ PARTIALLY PAID  ──  Lakshmi Constructions  ──  15 × Screwdriver
  // ════════════════════════════════════════════════════════════════════
  {
    id: 2,
    invoiceNumber: 'INV-2026-002',
    invoiceDate: '2026-01-15',
    dueDate: '2026-02-14',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'duplicate',
    companyBankDetails: BANK_HDFC,
    financialYear: 'FY 2025-26',
    referencePONo: 'CPO-002',
    currency: 'INR',
    exchangeRate: 1,
    status: 'partially_paid',
    eWayBillNo: 'EWB1002',
    deliveryNote: 'Partially Delivered',
    modeTermsOfPayment: 'Cash',
    buyerOrderNo: 'BO-002',
    buyerOrderDate: '2026-01-12',
    otherReferences: 'REF-002',
    dispatchDocNo: 'DOC-002',
    deliveryNoteDate: '2026-01-15',
    dispatchedThrough: 'Courier',
    destination: 'Chennai',
    billOfLadingNo: 'BL-002',
    motorVehicleNo: 'TN02CD5678',
    termsOfDelivery: 'Within 7 Days',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C002',
    customerName: 'Lakshmi Constructions',
    billingAddress: 'Anna Nagar, Chennai',
    shippingAddress: 'Anna Nagar, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600040',
    customerGSTIN: '33FGHIJ5678K1Z2',
    customerPAN: 'FGHIJ5678K',
    phoneEmail: '+91 9876543211 | lakshmi@constructions.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-010', productCode: 'HARD002',
        itemName: 'Screwdriver Set 6pc', hsnSacCode: '8205',
        quantity: 15, unitOfMeasure: 'Box', unitPrice: 449, unitId: 4,
        taxPercent: 18, discountPercent: 5, taxableAmount: 6398.25,
        gstRate: 18, cgstAmount: 575.84, sgstAmount: 575.84, igstAmount: 0,
        lineTotal: 7549.93, batchSerialNo: 'B002', taxId: 'T18',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '8205', taxableValue: 6398.25, cgstRate: 9, cgstAmount: 575.84, sgstRate: 9, sgstAmount: 575.84, igstRate: 0, igstAmount: 0, totalTaxAmount: 1151.68 },
    ],
    taxSummary: {
      subTotal: 6735, totalTaxableValue: 6398.25,
      totalCGST: 575.84, totalSGST: 575.84, totalIGST: 0,
      totalTaxAmount: 1151.68, grandTotal: 7549.93, roundOff: 0.07,
      invoiceTotal: 7550,
      amountInWords: 'Rupees Seven Thousand Five Hundred Fifty Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: 'cash',
      amountPaid: 4000, paymentDate: '2026-01-20',
      transactionRefNo: 'TXN002', balanceDue: 3550,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'partial',
    },
    declaration: 'Certified true copy.',
    notes: 'Partial payment received.',
    createdAt: '2026-01-15', updatedAt: '2026-01-20',
  },

  // ════════════════════════════════════════════════════════════════════
  //  3 ─ OVERDUE  ──  Sri Balaji  ──  20 × Wireless Mouse
  // ════════════════════════════════════════════════════════════════════
  {
    id: 3,
    invoiceNumber: 'INV-2026-003',
    invoiceDate: '2026-02-05',
    dueDate: '2026-02-20',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'triplicate',
    companyBankDetails: BANK_AXIS,
    financialYear: 'FY 2025-26',
    referencePONo: '',
    currency: 'INR',
    exchangeRate: 1,
    status: 'overdue',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C003',
    customerName: 'Sri Balaji Enterprises',
    billingAddress: 'Velachery, Chennai',
    shippingAddress: 'Velachery, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600042',
    customerGSTIN: '33LMNOP9012Q1Z7',
    customerPAN: 'LMNOP9012Q',
    phoneEmail: '+91 9876543212 | balaji@enterprises.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-002', productCode: 'ELEC002',
        itemName: 'Wireless Mouse MX3', hsnSacCode: '8471',
        quantity: 20, unitOfMeasure: 'Pcs', unitPrice: 1599, unitId: 1,
        taxPercent: 18, discountPercent: 0, taxableAmount: 31980,
        gstRate: 18, cgstAmount: 2878.20, sgstAmount: 2878.20, igstAmount: 0,
        lineTotal: 37736.40, batchSerialNo: 'B003', taxId: 'T18',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '8471', taxableValue: 31980, cgstRate: 9, cgstAmount: 2878.20, sgstRate: 9, sgstAmount: 2878.20, igstRate: 0, igstAmount: 0, totalTaxAmount: 5756.40 },
    ],
    taxSummary: {
      subTotal: 31980, totalTaxableValue: 31980,
      totalCGST: 2878.20, totalSGST: 2878.20, totalIGST: 0,
      totalTaxAmount: 5756.40, grandTotal: 37736.40, roundOff: 0.60,
      invoiceTotal: 37736,
      amountInWords: 'Rupees Thirty Seven Thousand Seven Hundred Thirty Six Only',
    },
    payment: {
      paymentTerms: 'net15', paymentMode: '',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 37736,
      overdueDays: 85, lateFeeInterest: 1200,
      paymentStatus: 'overdue',
    },
    declaration: 'Subject to Chennai jurisdiction.',
    notes: 'Payment overdue – follow-up sent.',
    createdAt: '2026-02-05', updatedAt: '2026-04-01',
  },

  // ════════════════════════════════════════════════════════════════════
  //  4 ─ SENT  ──  Arjun Traders  ──  50 × USB Cable
  // ════════════════════════════════════════════════════════════════════
  {
    id: 4,
    invoiceNumber: 'INV-2026-004',
    invoiceDate: '2026-02-15',
    dueDate: '2026-03-17',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_SBI,
    financialYear: 'FY 2025-26',
    referencePONo: 'CPO-004',
    currency: 'INR',
    exchangeRate: 1,
    status: 'sent',
    eWayBillNo: 'EWB1004',
    deliveryNote: 'Dispatched',
    modeTermsOfPayment: 'Cheque',
    buyerOrderNo: 'BO-004',
    buyerOrderDate: '2026-02-12',
    otherReferences: 'REF-004',
    dispatchDocNo: 'DOC-004',
    deliveryNoteDate: '2026-02-15',
    dispatchedThrough: 'Courier',
    destination: 'Chennai',
    billOfLadingNo: 'BL-004',
    motorVehicleNo: 'TN04GH1234',
    termsOfDelivery: '7 Days',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C001',
    customerName: 'Arjun Traders Pvt Ltd',
    billingAddress: 'T Nagar, Chennai',
    shippingAddress: 'T Nagar, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600017',
    customerGSTIN: '33ABCDE1234F1Z5',
    customerPAN: 'ABCDE1234F',
    phoneEmail: '+91 9876543210 | arjun@traders.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-007', productCode: 'ELEC003',
        itemName: 'USB Cable Type-C', hsnSacCode: '8544',
        quantity: 50, unitOfMeasure: 'Pcs', unitPrice: 149, unitId: 1,
        taxPercent: 18, discountPercent: 0, taxableAmount: 7450,
        gstRate: 18, cgstAmount: 670.50, sgstAmount: 670.50, igstAmount: 0,
        lineTotal: 8791, batchSerialNo: 'B004', taxId: 'T18',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '8544', taxableValue: 7450, cgstRate: 9, cgstAmount: 670.50, sgstRate: 9, sgstAmount: 670.50, igstRate: 0, igstAmount: 0, totalTaxAmount: 1341 },
    ],
    taxSummary: {
      subTotal: 7450, totalTaxableValue: 7450,
      totalCGST: 670.50, totalSGST: 670.50, totalIGST: 0,
      totalTaxAmount: 1341, grandTotal: 8791, roundOff: 0,
      invoiceTotal: 8791,
      amountInWords: 'Rupees Eight Thousand Seven Hundred Ninety One Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: 'cheque',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 8791,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'unpaid',
    },
    declaration: 'Goods once sold will not be taken back.',
    notes: 'Awaiting payment.',
    createdAt: '2026-02-15', updatedAt: '2026-02-15',
  },

  // ════════════════════════════════════════════════════════════════════
  //  5 ─ PAID  ──  Deepa Interiors  ──  3 × Laptop Pro 15
  // ════════════════════════════════════════════════════════════════════
  {
    id: 5,
    invoiceNumber: 'INV-2026-005',
    invoiceDate: '2026-03-01',
    dueDate: '2026-03-31',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_INDIAN,
    financialYear: 'FY 2025-26',
    referencePONo: 'CPO-005',
    currency: 'INR',
    exchangeRate: 1,
    status: 'paid',
    eWayBillNo: 'EWB1005',
    deliveryNote: 'Delivered',
    modeTermsOfPayment: 'UPI',
    buyerOrderNo: 'BO-005',
    buyerOrderDate: '2026-02-28',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C004',
    customerName: 'Deepa Interiors',
    billingAddress: 'Porur, Chennai',
    shippingAddress: 'Porur, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600116',
    customerGSTIN: '33QRSTU3456V1Z9',
    customerPAN: 'QRSTU3456V',
    phoneEmail: '+91 9876543213 | deepa@interiors.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-001', productCode: 'ELEC001',
        itemName: 'Laptop Pro 15', hsnSacCode: '8471',
        quantity: 3, unitOfMeasure: 'Pcs', unitPrice: 55000, unitId: 1,
        taxPercent: 18, discountPercent: 0, taxableAmount: 165000,
        gstRate: 18, cgstAmount: 14850, sgstAmount: 14850, igstAmount: 0,
        lineTotal: 194700, batchSerialNo: 'B005', taxId: 'T18',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '8471', taxableValue: 165000, cgstRate: 9, cgstAmount: 14850, sgstRate: 9, sgstAmount: 14850, igstRate: 0, igstAmount: 0, totalTaxAmount: 29700 },
    ],
    taxSummary: {
      subTotal: 165000, totalTaxableValue: 165000,
      totalCGST: 14850, totalSGST: 14850, totalIGST: 0,
      totalTaxAmount: 29700, grandTotal: 194700, roundOff: 0,
      invoiceTotal: 194700,
      amountInWords: 'Rupees One Lakh Ninety Four Thousand Seven Hundred Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: 'upi',
      amountPaid: 194700, paymentDate: '2026-03-10',
      transactionRefNo: 'TXN005', balanceDue: 0,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'paid',
    },
    notes: 'Paid via UPI. 1 unit returned as defective – credit note pending.',
    createdAt: '2026-03-01', updatedAt: '2026-03-10',
  },

  // ════════════════════════════════════════════════════════════════════
  //  6 ─ DRAFT  ──  Murugan Agencies  ──  10 × Cotton T-Shirt
  // ════════════════════════════════════════════════════════════════════
  {
    id: 6,
    invoiceNumber: 'INV-2026-006',
    invoiceDate: '2026-03-20',
    dueDate: null,
    invoiceType: 'tax_invoice',
    financialYear: 'FY 2025-26',
    referencePONo: '',
    currency: 'INR',
    exchangeRate: 1,
    status: 'draft',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C005',
    customerName: 'Murugan Agencies',
    billingAddress: 'Tambaram, Chennai',
    shippingAddress: 'Tambaram, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600045',
    customerGSTIN: '33WXYZ04567A1Z3',
    customerPAN: 'WXYZ04567A',
    phoneEmail: '+91 9876543214 | murugan@agencies.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-003', productCode: 'CLOTH001',
        itemName: 'Cotton T-Shirt - Blue', hsnSacCode: '6109',
        quantity: 10, unitOfMeasure: 'Pcs', unitPrice: 499, unitId: 1,
        taxPercent: 12, discountPercent: 0, taxableAmount: 4990,
        gstRate: 12, cgstAmount: 299.40, sgstAmount: 299.40, igstAmount: 0,
        lineTotal: 5588.80, batchSerialNo: '', taxId: 'T12',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '6109', taxableValue: 4990, cgstRate: 6, cgstAmount: 299.40, sgstRate: 6, sgstAmount: 299.40, igstRate: 0, igstAmount: 0, totalTaxAmount: 598.80 },
    ],
    taxSummary: {
      subTotal: 4990, totalTaxableValue: 4990,
      totalCGST: 299.40, totalSGST: 299.40, totalIGST: 0,
      totalTaxAmount: 598.80, grandTotal: 5588.80, roundOff: 0.20,
      invoiceTotal: 5589,
      amountInWords: 'Rupees Five Thousand Five Hundred Eighty Nine Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: '',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 5589,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'unpaid',
    },
    notes: 'Draft – pending review before sending.',
    createdAt: '2026-03-20', updatedAt: '2026-03-20',
  },

  // ════════════════════════════════════════════════════════════════════
  //  7 ─ SENT  ──  Kavitha Electronics  ──  5 × Organic Honey
  // ════════════════════════════════════════════════════════════════════
  {
    id: 7,
    invoiceNumber: 'INV-2026-007',
    invoiceDate: '2026-03-08',
    dueDate: '2026-04-07',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_HDFC,
    financialYear: 'FY 2025-26',
    referencePONo: 'CPO-007',
    currency: 'INR',
    exchangeRate: 1,
    status: 'sent',
    eWayBillNo: 'EWB1007',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C006',
    customerName: 'Kavitha Electronics',
    billingAddress: 'Chromepet, Chennai',
    shippingAddress: 'Chromepet, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600044',
    customerGSTIN: '33BCDEF6789G1Z1',
    customerPAN: 'BCDEF6789G',
    phoneEmail: '+91 9876543215 | kavitha@electronics.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-004', productCode: 'FOOD001',
        itemName: 'Organic Honey 500g', hsnSacCode: '0409',
        quantity: 5, unitOfMeasure: 'Pcs', unitPrice: 399, unitId: 2,
        taxPercent: 5, discountPercent: 0, taxableAmount: 1995,
        gstRate: 5, cgstAmount: 49.88, sgstAmount: 49.88, igstAmount: 0,
        lineTotal: 2094.76, batchSerialNo: 'B007', taxId: 'T5',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '0409', taxableValue: 1995, cgstRate: 2.5, cgstAmount: 49.88, sgstRate: 2.5, sgstAmount: 49.88, igstRate: 0, igstAmount: 0, totalTaxAmount: 99.76 },
    ],
    taxSummary: {
      subTotal: 1995, totalTaxableValue: 1995,
      totalCGST: 49.88, totalSGST: 49.88, totalIGST: 0,
      totalTaxAmount: 99.76, grandTotal: 2094.76, roundOff: 0.24,
      invoiceTotal: 2095,
      amountInWords: 'Rupees Two Thousand Ninety Five Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: '',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 2095,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'unpaid',
    },
    notes: 'Invoice sent via email.',
    createdAt: '2026-03-08', updatedAt: '2026-03-08',
  },

  // ════════════════════════════════════════════════════════════════════
  //  8 ─ OVERDUE  ──  Kavitha Electronics  ──  10 × Green Tea
  // ════════════════════════════════════════════════════════════════════
  {
    id: 8,
    invoiceNumber: 'INV-2026-008',
    invoiceDate: '2026-03-10',
    dueDate: '2026-03-25',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_AXIS,
    financialYear: 'FY 2025-26',
    referencePONo: '',
    currency: 'INR',
    exchangeRate: 1,
    status: 'overdue',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C006',
    customerName: 'Kavitha Electronics',
    billingAddress: 'Chromepet, Chennai',
    shippingAddress: 'Chromepet, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600044',
    customerGSTIN: '33BCDEF6789G1Z1',
    customerPAN: 'BCDEF6789G',
    phoneEmail: '+91 9876543215 | kavitha@electronics.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-011', productCode: 'FOOD002',
        itemName: 'Green Tea Bags 25pc', hsnSacCode: '0902',
        quantity: 10, unitOfMeasure: 'Box', unitPrice: 199, unitId: 4,
        taxPercent: 5, discountPercent: 0, taxableAmount: 1990,
        gstRate: 5, cgstAmount: 49.75, sgstAmount: 49.75, igstAmount: 0,
        lineTotal: 2089.50, batchSerialNo: 'B008', taxId: 'T5',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '0902', taxableValue: 1990, cgstRate: 2.5, cgstAmount: 49.75, sgstRate: 2.5, sgstAmount: 49.75, igstRate: 0, igstAmount: 0, totalTaxAmount: 99.50 },
    ],
    taxSummary: {
      subTotal: 1990, totalTaxableValue: 1990,
      totalCGST: 49.75, totalSGST: 49.75, totalIGST: 0,
      totalTaxAmount: 99.50, grandTotal: 2089.50, roundOff: 0.50,
      invoiceTotal: 2090,
      amountInWords: 'Rupees Two Thousand Ninety Only',
    },
    payment: {
      paymentTerms: 'net15', paymentMode: '',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 2090,
      overdueDays: 53, lateFeeInterest: 350,
      paymentStatus: 'overdue',
    },
    notes: 'Payment overdue. Reminder sent on 2026-04-05.',
    createdAt: '2026-03-10', updatedAt: '2026-04-05',
  },

  // ════════════════════════════════════════════════════════════════════
  //  9 ─ CANCELLED  ──  Arjun Traders  ──  8 × Denim Jeans
  // ════════════════════════════════════════════════════════════════════
  {
    id: 9,
    invoiceNumber: 'INV-2026-009',
    invoiceDate: '2026-03-22',
    dueDate: '2026-04-21',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_INDIAN,
    financialYear: 'FY 2025-26',
    referencePONo: '',
    currency: 'INR',
    exchangeRate: 1,
    status: 'cancelled',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C001',
    customerName: 'Arjun Traders Pvt Ltd',
    billingAddress: 'T Nagar, Chennai',
    shippingAddress: 'T Nagar, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600017',
    customerGSTIN: '33ABCDE1234F1Z5',
    customerPAN: 'ABCDE1234F',
    phoneEmail: '+91 9876543210 | arjun@traders.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-009', productCode: 'CLOTH002',
        itemName: 'Denim Jeans - Black', hsnSacCode: '6203',
        quantity: 8, unitOfMeasure: 'Pcs', unitPrice: 1299, unitId: 1,
        taxPercent: 12, discountPercent: 0, taxableAmount: 10392,
        gstRate: 12, cgstAmount: 623.52, sgstAmount: 623.52, igstAmount: 0,
        lineTotal: 11639.04, batchSerialNo: '', taxId: 'T12',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '6203', taxableValue: 10392, cgstRate: 6, cgstAmount: 623.52, sgstRate: 6, sgstAmount: 623.52, igstRate: 0, igstAmount: 0, totalTaxAmount: 1247.04 },
    ],
    taxSummary: {
      subTotal: 10392, totalTaxableValue: 10392,
      totalCGST: 623.52, totalSGST: 623.52, totalIGST: 0,
      totalTaxAmount: 1247.04, grandTotal: 11639.04, roundOff: -0.04,
      invoiceTotal: 11639,
      amountInWords: 'Rupees Eleven Thousand Six Hundred Thirty Nine Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: '',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 0,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'unpaid',
    },
    notes: 'Cancelled – customer withdrew order before dispatch.',
    createdAt: '2026-03-22', updatedAt: '2026-03-25',
  },

  // ════════════════════════════════════════════════════════════════════
  //  10 ─ PARTIALLY PAID  ──  Lakshmi Constructions  ──  12 × Steel Hammer
  // ════════════════════════════════════════════════════════════════════
  {
    id: 10,
    invoiceNumber: 'INV-2026-010',
    invoiceDate: '2026-04-01',
    dueDate: '2026-05-01',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_SBI,
    financialYear: 'FY 2025-26',
    referencePONo: 'CPO-010',
    currency: 'INR',
    exchangeRate: 1,
    status: 'partially_paid',
    eWayBillNo: 'EWB1010',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C002',
    customerName: 'Lakshmi Constructions',
    billingAddress: 'Anna Nagar, Chennai',
    shippingAddress: 'Anna Nagar, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600040',
    customerGSTIN: '33FGHIJ5678K1Z2',
    customerPAN: 'FGHIJ5678K',
    phoneEmail: '+91 9876543211 | lakshmi@constructions.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-005', productCode: 'HARD001',
        itemName: 'Steel Hammer 500g', hsnSacCode: '8205',
        quantity: 12, unitOfMeasure: 'Pcs', unitPrice: 299, unitId: 1,
        taxPercent: 18, discountPercent: 0, taxableAmount: 3588,
        gstRate: 18, cgstAmount: 322.92, sgstAmount: 322.92, igstAmount: 0,
        lineTotal: 4233.84, batchSerialNo: 'B010', taxId: 'T18',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '8205', taxableValue: 3588, cgstRate: 9, cgstAmount: 322.92, sgstRate: 9, sgstAmount: 322.92, igstRate: 0, igstAmount: 0, totalTaxAmount: 645.84 },
    ],
    taxSummary: {
      subTotal: 3588, totalTaxableValue: 3588,
      totalCGST: 322.92, totalSGST: 322.92, totalIGST: 0,
      totalTaxAmount: 645.84, grandTotal: 4233.84, roundOff: 0.16,
      invoiceTotal: 4234,
      amountInWords: 'Rupees Four Thousand Two Hundred Thirty Four Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: 'neft',
      amountPaid: 2000, paymentDate: '2026-04-10',
      transactionRefNo: 'TXN010', balanceDue: 2234,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'partial',
    },
    notes: 'Advance received. Balance due on delivery.',
    createdAt: '2026-04-01', updatedAt: '2026-04-10',
  },

  // ════════════════════════════════════════════════════════════════════
  //  11 ─ CANCELLED  ──  Deepa Interiors  ──  A4 Paper + Gel Pen
  // ════════════════════════════════════════════════════════════════════
  {
    id: 11,
    invoiceNumber: 'INV-2026-011',
    invoiceDate: '2026-04-05',
    dueDate: '2026-05-05',
    invoiceType: 'tax_invoice',
    invoiceCopyType: 'original',
    companyBankDetails: BANK_HDFC,
    financialYear: 'FY 2025-26',
    referencePONo: '',
    currency: 'INR',
    exchangeRate: 1,
    status: 'cancelled',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C004',
    customerName: 'Deepa Interiors',
    billingAddress: 'Porur, Chennai',
    shippingAddress: 'Porur, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600116',
    customerGSTIN: '33QRSTU3456V1Z9',
    customerPAN: 'QRSTU3456V',
    phoneEmail: '+91 9876543213 | deepa@interiors.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-006', productCode: 'STAT001',
        itemName: 'A4 Paper Ream', hsnSacCode: '4802',
        quantity: 20, unitOfMeasure: 'Ream', unitPrice: 299, unitId: 4,
        taxPercent: 12, discountPercent: 0, taxableAmount: 5980,
        gstRate: 12, cgstAmount: 358.80, sgstAmount: 358.80, igstAmount: 0,
        lineTotal: 6697.60, batchSerialNo: '', taxId: 'T12',
        errProduct: false, errQty: false, errPrice: false,
      },
      {
        sNo: 2, productId: 'prod-012', productCode: 'STAT002',
        itemName: 'Gel Pen - Blue', hsnSacCode: '9608',
        quantity: 100, unitOfMeasure: 'Pcs', unitPrice: 15, unitId: 5,
        taxPercent: 12, discountPercent: 0, taxableAmount: 1500,
        gstRate: 12, cgstAmount: 90, sgstAmount: 90, igstAmount: 0,
        lineTotal: 1680, batchSerialNo: '', taxId: 'T12',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '4802', taxableValue: 5980, cgstRate: 6, cgstAmount: 358.80, sgstRate: 6, sgstAmount: 358.80, igstRate: 0, igstAmount: 0, totalTaxAmount: 717.60 },
      { hsnSacCode: '9608', taxableValue: 1500, cgstRate: 6, cgstAmount: 90, sgstRate: 6, sgstAmount: 90, igstRate: 0, igstAmount: 0, totalTaxAmount: 180 },
    ],
    taxSummary: {
      subTotal: 7480, totalTaxableValue: 7480,
      totalCGST: 448.80, totalSGST: 448.80, totalIGST: 0,
      totalTaxAmount: 897.60, grandTotal: 8377.60, roundOff: 0.40,
      invoiceTotal: 8378,
      amountInWords: 'Rupees Eight Thousand Three Hundred Seventy Eight Only',
    },
    payment: {
      paymentTerms: 'net30', paymentMode: '',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 0,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'unpaid',
    },
    notes: 'Cancelled – duplicate order raised by customer.',
    createdAt: '2026-04-05', updatedAt: '2026-04-06',
  },

  // ════════════════════════════════════════════════════════════════════
  //  12 ─ DRAFT (Proforma)  ──  Murugan Agencies  ──  Installation Service
  // ════════════════════════════════════════════════════════════════════
  {
    id: 12,
    invoiceNumber: 'INV-2026-012',
    invoiceDate: '2026-04-12',
    dueDate: null,
    invoiceType: 'proforma',
    financialYear: 'FY 2025-26',
    referencePONo: '',
    currency: 'INR',
    exchangeRate: 1,
    status: 'draft',
    branchId: 'BR01',
    ...COMPANY,
    customerId: 'C005',
    customerName: 'Murugan Agencies',
    billingAddress: 'Tambaram, Chennai',
    shippingAddress: 'Tambaram, Chennai',
    cityStatePincode: 'Chennai, Tamil Nadu - 600045',
    customerGSTIN: '33WXYZ04567A1Z3',
    customerPAN: 'WXYZ04567A',
    phoneEmail: '+91 9876543214 | murugan@agencies.com',
    placeOfSupply: 'TN',
    lineItems: [
      {
        sNo: 1, productId: 'prod-008', productCode: 'SERV001',
        itemName: 'Installation Service', hsnSacCode: '9983',
        quantity: 2, unitOfMeasure: 'Nos', unitPrice: 599, unitId: 1,
        taxPercent: 18, discountPercent: 0, taxableAmount: 1198,
        gstRate: 18, cgstAmount: 107.82, sgstAmount: 107.82, igstAmount: 0,
        lineTotal: 1413.64, batchSerialNo: '', taxId: 'T18',
        errProduct: false, errQty: false, errPrice: false,
      },
    ],
    hsnWiseTaxSummary: [
      { hsnSacCode: '9983', taxableValue: 1198, cgstRate: 9, cgstAmount: 107.82, sgstRate: 9, sgstAmount: 107.82, igstRate: 0, igstAmount: 0, totalTaxAmount: 215.64 },
    ],
    taxSummary: {
      subTotal: 1198, totalTaxableValue: 1198,
      totalCGST: 107.82, totalSGST: 107.82, totalIGST: 0,
      totalTaxAmount: 215.64, grandTotal: 1413.64, roundOff: 0.36,
      invoiceTotal: 1414,
      amountInWords: 'Rupees One Thousand Four Hundred Fourteen Only',
    },
    payment: {
      paymentTerms: 'advance', paymentMode: '',
      amountPaid: 0, paymentDate: '',
      transactionRefNo: '', balanceDue: 1414,
      overdueDays: 0, lateFeeInterest: 0, paymentStatus: 'unpaid',
    },
    notes: 'Proforma invoice for service quotation.',
    createdAt: '2026-04-12', updatedAt: '2026-04-12',
  },
];
