import { Product } from './product';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    ProductId: 'prod-001',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00001',
    productName: 'Yashika 3+1+1 Sofa Set',
    categoryId: 1,
    categoryName: 'Sofa',
    subCategoryId: 101,
    subCategoryName: 'Fabric Sofa',
    brandId: 1,
    unitId: 4,
    barcode: '8904567001001',
    costPrice: 38500.0,
    sellingPrice: 62500.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 8,
    reorderLevel: 3,
    maxStockLevel: 20,
    description: 'Premium 3+1+1 sofa set with Sheesham wood frame, HD-32 density foam cushions, and beige linen upholstery. Includes 3-seater, two 1-seater chairs.',
    metaTagTitle: 'Yashika 3+1+1 Sofa Set',
    metaTagDescription: 'Luxurious 3+1+1 sofa set with solid wood frame and premium fabric.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-08-15',
    updatedAt: '2026-04-20',
  },
  {
    id: 2,
    ProductId: 'prod-002',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00002',
    productName: 'Royal Single Recliner',
    categoryId: 2,
    categoryName: 'Recliner',
    subCategoryId: 201,
    subCategoryName: 'Single Recliner',
    brandId: 3,
    unitId: 1,
    barcode: '8904567001002',
    costPrice: 21000.0,
    sellingPrice: 35000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'percentage',
    discountValue: 5,
    currentStock: 12,
    reorderLevel: 4,
    maxStockLevel: 25,
    description: 'Manual single recliner with leatherette upholstery, 3-position recline, and sturdy steel mechanism.',
    metaTagTitle: 'Royal Single Recliner',
    metaTagDescription: 'Comfortable manual recliner with leatherette finish.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-10-01',
    updatedAt: '2026-04-22',
  },
  {
    id: 3,
    ProductId: 'prod-003',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00003',
    productName: 'Milano L-Shape Sofa',
    categoryId: 1,
    categoryName: 'Sofa',
    subCategoryId: 103,
    subCategoryName: 'L-Shape Sofa',
    brandId: 1,
    unitId: 4,
    barcode: '8904567001003',
    costPrice: 52000.0,
    sellingPrice: 85000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 5,
    reorderLevel: 2,
    maxStockLevel: 12,
    description: 'Modern L-shape sectional sofa in velvet royal blue fabric with silver oak wood frame. Seats 6 comfortably.',
    metaTagTitle: 'Milano L-Shape Sofa',
    metaTagDescription: 'Contemporary L-shape sofa for spacious living rooms.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-11-10',
    updatedAt: '2026-04-25',
  },
  {
    id: 4,
    ProductId: 'prod-004',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00004',
    productName: 'Heritage 6-Seater Dining Set',
    categoryId: 3,
    categoryName: 'Dining',
    subCategoryId: 302,
    subCategoryName: '6-Seater Dining',
    brandId: 2,
    unitId: 4,
    barcode: '8904567001004',
    costPrice: 27000.0,
    sellingPrice: 45000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'fixed',
    discountValue: 2000,
    currentStock: 6,
    reorderLevel: 2,
    maxStockLevel: 15,
    description: 'Solid Sheesham wood 6-seater dining table with cushioned chairs. Natural teak oil finish.',
    metaTagTitle: 'Heritage 6-Seater Dining Set',
    metaTagDescription: 'Traditional solid wood dining set for family dining.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-09-20',
    updatedAt: '2026-03-10',
  },
  {
    id: 5,
    ProductId: 'prod-005',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00005',
    productName: 'Luxe King Bed with Storage',
    categoryId: 4,
    categoryName: 'Bed',
    subCategoryId: 403,
    subCategoryName: 'Storage Bed',
    brandId: 1,
    unitId: 1,
    barcode: '8904567001005',
    costPrice: 34000.0,
    sellingPrice: 58000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 4,
    reorderLevel: 2,
    maxStockLevel: 10,
    description: 'King-size hydraulic storage bed with upholstered headboard and engineered wood frame.',
    metaTagTitle: 'Luxe King Bed with Storage',
    metaTagDescription: 'King bed with hydraulic storage and cushioned headboard.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-12-01',
    updatedAt: '2026-04-18',
  },
  {
    id: 6,
    ProductId: 'prod-006',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00006',
    productName: 'Executive High-Back Chair',
    categoryId: 5,
    categoryName: 'Office Chair',
    subCategoryId: 501,
    subCategoryName: 'Executive Chair',
    brandId: 2,
    unitId: 1,
    barcode: '8904567001006',
    costPrice: 11000.0,
    sellingPrice: 18500.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'percentage',
    discountValue: 10,
    currentStock: 15,
    reorderLevel: 5,
    maxStockLevel: 30,
    description: 'Premium executive chair with genuine leather upholstery, lumbar support, and synchro-tilt mechanism.',
    metaTagTitle: 'Executive High-Back Chair',
    metaTagDescription: 'Ergonomic executive chair for office use.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2026-01-15',
    updatedAt: '2026-04-28',
  },
  {
    id: 7,
    ProductId: 'prod-007',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00007',
    productName: 'Comfort 2-Seater Loveseat',
    categoryId: 1,
    categoryName: 'Sofa',
    subCategoryId: 101,
    subCategoryName: 'Fabric Sofa',
    brandId: 2,
    unitId: 1,
    barcode: '8904567001007',
    costPrice: 17000.0,
    sellingPrice: 28000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 10,
    reorderLevel: 3,
    maxStockLevel: 20,
    description: 'Compact 2-seater loveseat with chenille grey fabric and solid wood legs. Perfect for apartments.',
    metaTagTitle: 'Comfort 2-Seater Loveseat',
    metaTagDescription: 'Compact loveseat sofa for small spaces.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2026-01-20',
    updatedAt: '2026-04-30',
  },
  {
    id: 8,
    ProductId: 'prod-008',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00008',
    productName: 'Sofa Assembly & Delivery',
    categoryId: 1,
    categoryName: 'Sofa',
    subCategoryId: 0,
    subCategoryName: '',
    brandId: undefined,
    unitId: 1,
    barcode: '',
    costPrice: 0,
    sellingPrice: 2500.0,
    taxId: 1,
    images: [],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 0,
    reorderLevel: 0,
    maxStockLevel: 0,
    description: 'Professional assembly and white-glove delivery service for all sofa and furniture products.',
    metaTagTitle: 'Sofa Assembly & Delivery',
    metaTagDescription: 'Professional furniture assembly and delivery service.',
    isPhysical: false,
    productTemplate: '',
    status: 'active',
    ProductType: 'Service (labour, delivery)',
    createdAt: '2026-01-05',
    updatedAt: '2026-04-20',
  },
  {
    id: 9,
    ProductId: 'prod-009',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00009',
    productName: 'Throne Motorised Recliner',
    categoryId: 2,
    categoryName: 'Recliner',
    subCategoryId: 203,
    subCategoryName: 'Motorised Recliner',
    brandId: 3,
    unitId: 1,
    barcode: '8904567001009',
    costPrice: 45000.0,
    sellingPrice: 72000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: true,
    discountType: 'percentage',
    discountValue: 8,
    currentStock: 3,
    reorderLevel: 2,
    maxStockLevel: 8,
    description: 'Top-of-the-line motorised recliner with genuine leather, USB charging, and memory foam headrest.',
    metaTagTitle: 'Throne Motorised Recliner',
    metaTagDescription: 'Premium motorised recliner with leather finish.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-07-10',
    updatedAt: '2026-01-30',
  },
  {
    id: 10,
    ProductId: 'prod-010',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00010',
    productName: 'Classic 3-Seater Chesterfield',
    categoryId: 1,
    categoryName: 'Sofa',
    subCategoryId: 102,
    subCategoryName: 'Leather Sofa',
    brandId: 1,
    unitId: 1,
    barcode: '8904567001010',
    costPrice: 58000.0,
    sellingPrice: 95000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1550254478-ead40cc54513?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 2,
    reorderLevel: 1,
    maxStockLevel: 6,
    description: 'Hand-tufted Chesterfield sofa in genuine tan leather with rolled arms and turned wooden legs.',
    metaTagTitle: 'Classic 3-Seater Chesterfield',
    metaTagDescription: 'Timeless Chesterfield sofa in genuine leather.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-06-01',
    updatedAt: '2026-04-26',
  },
  {
    id: 11,
    ProductId: 'prod-011',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00011',
    productName: 'Minimal 4-Seater Dining Set',
    categoryId: 3,
    categoryName: 'Dining',
    subCategoryId: 301,
    subCategoryName: '4-Seater Dining',
    brandId: 2,
    unitId: 4,
    barcode: '8904567001011',
    costPrice: 19500.0,
    sellingPrice: 32000.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 9,
    reorderLevel: 3,
    maxStockLevel: 18,
    description: 'Modern minimalist 4-seater dining table with cushioned chairs. Engineered wood with PU finish.',
    metaTagTitle: 'Minimal 4-Seater Dining Set',
    metaTagDescription: 'Contemporary 4-seater dining set.',
    isPhysical: true,
    productTemplate: '',
    status: 'inactive',
    ProductType: 'Goods',
    createdAt: '2025-10-15',
    updatedAt: '2026-03-20',
  },
  {
    id: 12,
    ProductId: 'prod-012',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'PRD-00012',
    productName: 'Ergonomic Mesh Office Chair',
    categoryId: 5,
    categoryName: 'Office Chair',
    subCategoryId: 502,
    subCategoryName: 'Ergonomic Chair',
    brandId: 2,
    unitId: 1,
    barcode: '8904567001012',
    costPrice: 8500.0,
    sellingPrice: 14500.0,
    taxId: 1,
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&h=400&fit=crop', isPrimary: true },
    ],
    isInclusiveTax: false,
    discountType: 'percentage',
    discountValue: 10,
    currentStock: 20,
    reorderLevel: 5,
    maxStockLevel: 40,
    description: 'Breathable mesh back ergonomic chair with adjustable lumbar, 3D armrests, and nylon base.',
    metaTagTitle: 'Ergonomic Mesh Office Chair',
    metaTagDescription: 'Premium ergonomic office chair with mesh back.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2026-03-01',
    updatedAt: '2026-04-30',
  },
];
export const INITIAL_NEXT_ID = INITIAL_PRODUCTS.length + 1;
