import { Product } from './product';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    ProductId: 'prod-001',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'ELEC001',
    productName: 'Laptop Pro 15',
    categoryId: 1,
    categoryName: 'Electronics',
    brandId: 1,
    unitId: 1,
    barcode: '8901234567890',
    costPrice: 48000.0,
    sellingPrice: 55000.0,
    taxId: 1,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 24,
    reorderLevel: 5,
    maxStockLevel: 100,
    description: 'High-performance 15-inch laptop with Intel i7 processor, 16GB RAM, and 512GB SSD.',
    metaTagTitle: 'Laptop Pro 15',
    metaTagDescription: 'Professional grade laptop for business users.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2024-06-15',
    updatedAt: '2025-04-20',
  },
  {
    id: 2,
    ProductId: 'prod-002',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'ELEC002',
    productName: 'Wireless Mouse MX3',
    categoryId: 1,
    categoryName: 'Electronics',
    brandId: 2,
    unitId: 1,
    barcode: '8901234567891',
    costPrice: 1200.0,
    sellingPrice: 1599.0,
    taxId: 1,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'percentage',
    discountValue: 10,
    currentStock: 150,
    reorderLevel: 20,
    maxStockLevel: 300,
    description: 'Ergonomic wireless mouse with adjustable DPI and long battery life.',
    metaTagTitle: 'Wireless Mouse MX3',
    metaTagDescription: 'Premium wireless mouse for productivity.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-01-10',
    updatedAt: '2025-04-22',
  },
  {
    id: 3,
    ProductId: 'prod-003',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'CLOTH001',
    productName: 'Cotton T-Shirt - Blue',
    categoryId: 2,
    categoryName: 'Clothing',
    brandId: 1,
    unitId: 1,
    barcode: '8901234567892',
    costPrice: 250.0,
    sellingPrice: 499.0,
    taxId: 2,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: true,
    discountType: 'none',
    discountValue: null,
    currentStock: 85,
    reorderLevel: 15,
    maxStockLevel: 200,
    description: '100% premium cotton t-shirt, comfortable fit, available in multiple sizes.',
    metaTagTitle: 'Cotton T-Shirt Blue',
    metaTagDescription: 'Premium quality cotton t-shirt.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-02-05',
    updatedAt: '2025-04-25',
  },
  {
    id: 4,
    ProductId: 'prod-004',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'FOOD001',
    productName: 'Organic Honey 500g',
    categoryId: 3,
    categoryName: 'Food & Beverages',
    brandId: 1,
    unitId: 2,
    barcode: '8901234567893',
    costPrice: 280.0,
    sellingPrice: 399.0,
    taxId: 3,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1587049352846-4a222e784l67?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'fixed',
    discountValue: 50,
    currentStock: 42,
    reorderLevel: 10,
    maxStockLevel: 100,
    description: 'Pure organic honey sourced from natural farms. Rich in nutrients.',
    metaTagTitle: 'Organic Honey',
    metaTagDescription: 'Natural organic honey 500g jar.',
    isPhysical: true,
    productTemplate: '',
    status: 'inactive',
    ProductType: 'Goods',
    createdAt: '2024-11-20',
    updatedAt: '2025-03-10',
  },
  {
    id: 5,
    ProductId: 'prod-005',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'HARD001',
    productName: 'Steel Hammer 500g',
    categoryId: 4,
    categoryName: 'Hardware',
    brandId: 2,
    unitId: 1,
    barcode: '8901234567894',
    costPrice: 180.0,
    sellingPrice: 299.0,
    taxId: 1,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 68,
    reorderLevel: 10,
    maxStockLevel: 150,
    description: 'Heavy-duty steel hammer with comfortable grip handle.',
    metaTagTitle: 'Steel Hammer',
    metaTagDescription: 'Professional grade steel hammer.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-01-15',
    updatedAt: '2025-04-18',
  },
  {
    id: 6,
    ProductId: 'prod-006',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'STAT001',
    productName: 'A4 Paper Ream',
    categoryId: 5,
    categoryName: 'Stationery',
    brandId: 1,
    unitId: 4,
    barcode: '8901234567895',
    costPrice: 220.0,
    sellingPrice: 299.0,
    taxId: 2,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'percentage',
    discountValue: 5,
    currentStock: 120,
    reorderLevel: 30,
    maxStockLevel: 300,
    description: 'Premium quality A4 paper, 500 sheets per ream, 80 GSM.',
    metaTagTitle: 'A4 Paper',
    metaTagDescription: 'High quality A4 printing paper.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-01-20',
    updatedAt: '2025-04-28',
  },
  {
    id: 7,
    ProductId: 'prod-007',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'ELEC003',
    productName: 'USB Cable Type-C',
    categoryId: 1,
    categoryName: 'Electronics',
    brandId: 3,
    unitId: 1,
    barcode: '8901234567896',
    costPrice: 80.0,
    sellingPrice: 149.0,
    taxId: 1,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1591290619762-c3790e2edd3a?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 200,
    reorderLevel: 50,
    maxStockLevel: 500,
    description: 'Fast charging USB Type-C cable, 1 meter length, durable design.',
    metaTagTitle: 'USB Cable Type-C',
    metaTagDescription: 'Fast charging USB Type-C cable.',
    isPhysical: true,
    productTemplate: '',
    status: 'inactive',
    ProductType: 'Goods',
    createdAt: '2024-12-10',
    updatedAt: '2025-02-15',
  },
  {
    id: 8,
    ProductId: 'prod-008',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'SERV001',
    productName: 'Installation Service',
    categoryId: 1,
    categoryName: 'Electronics',
    brandId: 1,
    unitId: 1,
    barcode: '',
    costPrice: 0,
    sellingPrice: 599.0,
    taxId: 1,
    images: [],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 0,
    reorderLevel: 0,
    maxStockLevel: 0,
    description: 'Professional installation and setup service for electronic equipment.',
    metaTagTitle: 'Installation Service',
    metaTagDescription: 'Professional installation service.',
    isPhysical: false,
    productTemplate: '',
    status: 'active',
    ProductType: 'Service (labour, delivery)',
    createdAt: '2025-01-05',
    updatedAt: '2025-04-20',
  },
  {
    id: 9,
    ProductId: 'prod-009',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'CLOTH002',
    productName: 'Denim Jeans - Black',
    categoryId: 2,
    categoryName: 'Clothing',
    brandId: 2,
    unitId: 1,
    barcode: '8901234567897',
    costPrice: 800.0,
    sellingPrice: 1299.0,
    taxId: 2,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: true,
    discountType: 'percentage',
    discountValue: 15,
    currentStock: 45,
    reorderLevel: 10,
    maxStockLevel: 100,
    description: 'Premium black denim jeans, slim fit, durable fabric.',
    metaTagTitle: 'Denim Jeans Black',
    metaTagDescription: 'Stylish black denim jeans.',
    isPhysical: true,
    productTemplate: '',
    status: 'discontinued',
    ProductType: 'Goods',
    createdAt: '2024-08-10',
    updatedAt: '2025-01-30',
  },
  {
    id: 10,
    ProductId: 'prod-0010',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'HARD002',
    productName: 'Screwdriver Set 6pc',
    categoryId: 4,
    categoryName: 'Hardware',
    brandId: 2,
    unitId: 4,
    barcode: '8901234567898',
    costPrice: 280.0,
    sellingPrice: 449.0,
    taxId: 1,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'fixed',
    discountValue: 50,
    currentStock: 92,
    reorderLevel: 15,
    maxStockLevel: 200,
    description: 'Professional 6-piece screwdriver set with magnetic tips.',
    metaTagTitle: 'Screwdriver Set',
    metaTagDescription: '6-piece professional screwdriver set.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-02-01',
    updatedAt: '2025-04-26',
  },
  {
    id: 11,
    ProductId: 'prod-0011',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'FOOD002',
    productName: 'Green Tea Bags 25pc',
    categoryId: 3,
    categoryName: 'Food & Beverages',
    brandId: 3,
    unitId: 4,
    barcode: '8901234567899',
    costPrice: 110.0,
    sellingPrice: 199.0,
    taxId: 3,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1594631661960-e62f0ab101dc?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'none',
    discountValue: null,
    currentStock: 78,
    reorderLevel: 20,
    maxStockLevel: 150,
    description: 'Premium green tea bags, rich in antioxidants, 25 tea bags per pack.',
    metaTagTitle: 'Green Tea',
    metaTagDescription: 'Healthy green tea bags.',
    isPhysical: true,
    productTemplate: '',
    status: 'inactive',
    ProductType: 'Goods',
    createdAt: '2024-10-15',
    updatedAt: '2025-03-20',
  },
  {
    id: 12,
    ProductId: 'prod-0012',
    TenantId: crypto.randomUUID(),
    CompanyId: crypto.randomUUID(),
    productCode: 'STAT002',
    productName: 'Gel Pen - Blue',
    categoryId: 5,
    categoryName: 'Stationery',
    brandId: 1,
    unitId: 5,
    barcode: '8901234567900',
    costPrice: 8.0,
    sellingPrice: 15.0,
    taxId: 2,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=600&h=400&fit=crop',
        isPrimary: true,
      },
    ],
    isInclusiveTax: false,
    discountType: 'percentage',
    discountValue: 10,
    currentStock: 500,
    reorderLevel: 100,
    maxStockLevel: 1000,
    description: 'Smooth writing gel pen with comfortable grip, 0.7mm tip.',
    metaTagTitle: 'Gel Pen Blue',
    metaTagDescription: 'Premium gel pen for smooth writing.',
    isPhysical: true,
    productTemplate: '',
    status: 'active',
    ProductType: 'Goods',
    createdAt: '2025-03-01',
    updatedAt: '2025-04-30',
  },
];

export const INITIAL_NEXT_ID = INITIAL_PRODUCTS.length + 1;
